<a href="https://colab.research.google.com/github/pranukrish/CMPE258_DeepLearning/blob/main/Assignment2-b/EinSum_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This colab demonstrates the below operations using einsum in Tensorflow



1.   Scalar Vector Multiplication
2.   Vector Vector Multiplications
3.   Outer Product
4.   Scalar Dot Product
5.   Hadamard Product
6.   Batch Matrix Multiplication
7.   Tensor Reduction
8.   Transpose
9.   Bilinear Transformation
10.   Attention
11.   Tree QN


In [ ]:
import tensorflow as tf
import torch.nn.functional as F
from tensorflow.keras.layers import Dense, Softmax

**a) Scalar-Vector Multiplication**

In [ ]:
scalar = tf.constant([4])
vector = tf.constant([1, 3, 4])
print(scalar)
print(vector)
print(tf.einsum("i,j->j", scalar, vector))

scalar = 6
vector = tf.constant([3,4,5])
print(tf.multiply(scalar, vector))

tf.Tensor([4], shape=(1,), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor([ 4 12 16], shape=(3,), dtype=int32)
tf.Tensor([18 24 30], shape=(3,), dtype=int32)


**b) Vector-Vector multiplications**

In [ ]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6,7])
tf.einsum('i,j->ij', a, b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21]], dtype=int32)>

**3) Outer Product**

In [ ]:
vector  = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[1,2,3]])
tf.einsum("i,ji->j", vector, matrix)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([14, 14], dtype=int32)>

**4) Scalar Dot Product**

In [ ]:
import torch

a = torch.tensor([1, 2, 3])
s = 2
result = torch.einsum('i,i->', s*a, a)

print(result)


tensor(28)


**5) Hadamard Product**

In [ ]:
mat1 = tf.constant([[1,2,3],[4,5,6]])
mat2 = tf.constant([[1,2,3],[4,5,6]])
tf.einsum("ij,ij->ij",mat1,mat2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

**6) Batch Matrix Multiplication**

In [ ]:
a = tf.random.uniform(shape=(3,2,5), minval=-10.0, maxval=10.0)
b = tf.random.uniform(shape=(3,5,3), minval=-10.0, maxval=10.0)
print(a)
print(b)
tf.einsum('ijk,ikl->ijl', a, b)

tf.Tensor(
[[[ 0.2541685   7.8953934  -8.42758    -9.780831    8.763466  ]
  [ 3.567195    8.728798    7.8437138  -7.973497    4.3910294 ]]

 [[ 2.776904    1.3952045   1.5529842  -1.4512081   0.29194355]
  [-8.382516   -0.1637268   4.0471954   1.9388466   3.5329008 ]]

 [[ 7.2604084   2.9894428   2.7903385   0.08502197  1.1647177 ]
  [ 7.398144    7.597786   -1.4556217  -2.7853703   7.671425  ]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(
[[[-0.58499146  6.2910385  -8.025892  ]
  [-8.497481    2.7615356   6.6413803 ]
  [-3.168826    0.640769    0.80663204]
  [-5.126536   -4.3568087  -4.2745996 ]
  [ 3.4997368   8.674116   -4.6977615 ]]

 [[ 2.006693   -6.6270566  -0.5589504 ]
  [ 6.9808807   6.6144466   3.143608  ]
  [-7.785518   -7.4216795  -5.1826644 ]
  [ 1.4026909   2.2329903  -7.347367  ]
  [-7.9124546   9.204905   -1.7181826 ]]

 [[ 7.0373173  -1.4391117   3.3779354 ]
  [-1.7139959   9.086187   -6.4780426 ]
  [ 5.9033756  -3.8361096  -5.0154376 ]
  [ 7.9668846   3.9908142   6.5

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 40.277496 , 136.6308   ,  44.238888 ],
        [-44.87108  , 124.39957  ,  49.12384  ]],

       [[ -1.1242225, -21.253166 ,   4.9461746],
        [-74.707924 ,  61.2809   , -37.120125 ]],

       [[ 69.59197  ,  15.026173 ,  -7.950617 ],
        [ 50.886528 , 110.00607  , -32.960632 ]]], dtype=float32)>

**7) Tensor Reduction**

In [ ]:
a = tf.random.uniform(shape=(2,17,5,7), minval=-10.0, maxval=10.0)
b = tf.random.uniform(shape=(11,2,4,17,6), minval=-10.0, maxval=10.0)

tf.einsum('pqrs,tpwqm->rstwm', a, b).shape

TensorShape([5, 7, 11, 4, 6])

**8) Transpose**

In [ ]:
print(tf.einsum("ij -> ji", x))

tf.Tensor(
[[-9.445949  -1.5855675]
 [-1.4914627 -4.36615  ]
 [-5.994127  -3.192091 ]], shape=(3, 2), dtype=float32)


**9) Bilinear Transformation**

In [ ]:
a = tf.random.uniform(shape=(2,3), minval=-10.0, maxval=10.0)
b = tf.random.uniform(shape=(5,3,7), minval=-10.0, maxval=10.0)
c = tf.random.uniform(shape=(2,7), minval=-10.0, maxval=10.0)
tf.einsum('ik,jkl,il->ij', a, b, c)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[ -355.03607 ,  2456.266   ,  -607.8041  ,  -703.4442  ,
         1162.8785  ],
       [  -16.474762,  -812.6148  ,   989.0173  ,   403.2178  ,
        -1179.567   ]], dtype=float32)>

**10) Attention**

In [ ]:
bM, br, w = random_tensors([7], num=3, requires_grad=True)
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

print(bM, br, w)
print(WY, Wh, Wr, Wt)

def attention(Y, ht, rt1):
    
    #tanh return a new tensor with the hyperbolic tangent of the given input
    #unsqueeze is to get a tensor add insert an additional dimension at the given position
    tmp = tf.einsum("ik,kl->il", ht, Wh) + tf.einsum("ik,kl->il", rt1, Wr)
    Mt = tf.math.tanh(tf.einsum("ijk,kl->ijl", Y, WY) + tf.expand_dims(tmp, 1) + bM)
    
    #applying softmax : expression/sigma expression
    at = Softmax(axis=1)(tf.einsum("ijk,k->ij", Mt, w))
    
    
    rt = tf.einsum("ijk,ij->ik", Y, at) + tf.math.tanh(tf.einsum("ij,jk->ik", rt1, Wt) + br)
    
    return rt, at

Y = tf.constant(tf.random.normal([3, 5, 7]))

ht, rt1 = random_tensors([3, 7], num=2)

print(ht)
print(rt1)

rt, at = attention(Y, ht, rt1)
print(at) 

<tf.Variable 'Variable:0' shape=(7,) dtype=float32, numpy=
array([-0.04998465,  0.6842691 , -0.19926485, -0.5937128 ,  0.4735706 ,
       -1.3880353 ,  0.23904517], dtype=float32)> <tf.Variable 'Variable:0' shape=(7,) dtype=float32, numpy=
array([-0.30687287,  0.07625407,  1.685044  ,  0.24431336, -0.11394605,
        0.6287942 , -0.7672582 ], dtype=float32)> <tf.Variable 'Variable:0' shape=(7,) dtype=float32, numpy=
array([-1.3750788 ,  1.4400314 , -0.7351835 ,  0.6862943 ,  0.52089906,
        0.7646337 , -0.36845043], dtype=float32)>
<tf.Variable 'Variable:0' shape=(7, 7) dtype=float32, numpy=
array([[-0.66859835, -0.26166663,  0.4333114 ,  0.90375   , -0.76918316,
        -0.8667706 , -1.3205879 ],
       [ 0.30185565, -0.3002777 ,  0.07431067, -1.09158   ,  0.12638527,
         0.0769187 , -1.064051  ],
       [ 2.4975307 ,  0.43343407,  1.206616  ,  1.3718984 ,  0.9905324 ,
        -1.6093754 ,  0.7699465 ],
       [-2.321177  ,  0.8535951 , -0.6347902 , -0.556702  , -0.78069746,

**11) Tree-QN**

In [ ]:
# Parameters
# -- [num_actions x hidden_dimension]
b = tf.Variable(tf.random.normal([5, 3]))
# -- [num_actions x hidden_dimension x hidden_dimension]
W = tf.Variable(tf.random.normal([5, 3, 3]))

print(b)
print(W)

def transition(zl):
  # -- [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, axis=1) + tf.math.tanh(tf.einsum("bk,aki->bai", zl, W) + b)

# Sampled dummy inputs
# -- [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])

print(zl)
print(transition(zl))

print(zl)

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float32, numpy=
array([[-1.9562919 ,  0.12045093, -1.2120464 ],
       [ 1.2429549 , -0.8839163 , -0.31442255],
       [ 0.03016904, -1.1759588 , -0.49798042],
       [ 0.99359417,  2.1689136 ,  1.0205982 ],
       [-1.2921035 ,  0.18344359, -0.17415787]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5, 3, 3) dtype=float32, numpy=
array([[[ 0.06897929, -0.9274958 , -0.33749667],
        [ 0.9238671 , -1.3626378 ,  0.73449755],
        [ 0.19184135, -0.5388543 ,  1.0990243 ]],

       [[-0.09707427,  0.79606813, -0.02579636],
        [-0.8147048 , -1.3487798 ,  0.6803449 ],
        [-1.2734554 , -0.56676716,  0.3548572 ]],

       [[-0.14542772,  1.1232524 , -0.34243685],
        [-1.4205145 ,  0.59253556,  0.23857316],
        [-1.3421371 , -0.3505149 ,  0.17085189]],

       [[-0.35782248, -0.08813392, -0.3321507 ],
        [-0.61321956,  0.6366898 ,  1.6965084 ],
        [ 0.5067405 ,  2.0297093 , -0.29067346]],

       [[-0.05708369, 