<a href="https://colab.research.google.com/github/pranukrish/CMPE258_DeepLearning/blob/main/Assignment2-b/EinSum_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This colab demonstrates the below operations using einsum in numpy



1.   Scalar Vector Multiplication
2.   Vector Vector Multiplications
3.   Outer Product
4.   Scalar Dot Product
5.   Hadamard Product
6.   Batch Matrix Multiplication
7.   Tensor Reduction
8.   Transpose
9.   Bilinear Transformation
10.   Attention
11.   Tree QN


**1) Scalar-Vector Multiplication**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
s = np.array([2])
result = np.einsum('i,j->j', s, a)

print(result)



[2 4 6]


**2) Vector-Vector multiplications**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,i->', a, b)

print(result)


32


**3) Outer Product**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,j->ij', a, b)

print(result)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**4) Scalar Dot Product**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
s = 2
result = np.einsum('i,i->', s*a, a)

print(result)


28


**5) Hadamard Product**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,i->i', a, b)

print(result)


[ 4 10 18]


**6) Batch Matrix Multiplication**

In [ ]:
import numpy as np

A = np.random.randn(3, 4, 5)  # 3 matrices of size 4x5
B = np.random.randn(3, 5, 6)  # 3 matrices of size 5x6

# Batch matrix multiplication
result = np.einsum('ijk,ikl->ijl', A, B)

print(result.shape)


(3, 4, 6)


**7) Tensor Reduction**

In [21]:
import numpy as np

# Create a 3D tensor
x = np.random.rand(3, 4, 5)

# Sum over the second dimension
result = np.einsum('ijk->ik', x)

print(result.shape)  


(3, 5)


**8) Transpose**

In [22]:
import numpy as np

# Create a matrix
x = np.random.rand(3, 4)

# Transpose the matrix
result = np.einsum('ij->ji', x)

print(result.shape) 


(4, 3)


**9) Bilinear Transformation**

In [23]:
import numpy as np

# Create two vectors
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Create a matrix
A = np.random.rand(3, 3)

# Compute the bilinear transformation of x and y
result = np.einsum('i,j,ij->', x, y, A)

print(result)  # a scalar value


63.51655977349586


**10) Attention**

In [24]:
import numpy as np

# Create a batch of input vectors and weights
x = np.random.rand(10, 3)
w = np.random.rand(3)

# Compute the attention weights
alpha = np.einsum('ij,j->i', x, w)

# Normalize the weights using softmax
alpha = np.exp(alpha) / np.sum(np.exp(alpha))

# Compute the weighted sum of the input vectors
result = np.einsum('ij,i->j', x, alpha)

print(result.shape)  


(3,)


**11) Tree-QN**

In [25]:
import numpy as np

# Define the embeddings for the large corpus
embeddings_large = np.random.rand(10000, 300)

# Define the embeddings for the task-specific corpus
embeddings_small = np.random.rand(100, 300)

# Compute the pairwise cosine similarities between the large corpus embeddings
sims_large = np.einsum('ij,ij->i', embeddings_large, embeddings_large)

# Compute the pairwise cosine similarities between the task-specific corpus embeddings
sims_small = np.einsum('ij,ij->i', embeddings_small, embeddings_small)

# Compute the cosine similarities between the large corpus embeddings and the task-specific corpus embeddings
sims_cross = np.einsum('ij,kj->ik', embeddings_small, embeddings_large)

# Compute the Tree-QN metric
n = len(embeddings_small)
diff = np.sum(np.square(sims_cross - np.outer(sims_small, sims_large) / n))
tree_qn = np.sqrt(diff / (n * (n - 1)))

print(tree_qn)


246.7055618347294
