<a href="https://colab.research.google.com/github/pranukrish/CMPE258_DeepLearning/blob/main/Assignment2-b/EinSum_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**a) Scalar-Vector Multiplication**

In [20]:
import numpy as np

a = np.array([1, 2, 3])
s = np.array([2])
result = np.einsum('i,j->j', s, a)

print(result)
# Output: [2 4 6]


[2 4 6]


**b) Vector-Vector multiplications **

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,i->', a, b)

print(result)


32


**3) Outer Product**

In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,j->ij', a, b)

print(result)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**4) Scalar Dot Product**

In [13]:
import numpy as np

a = np.array([1, 2, 3])
s = 2
result = np.einsum('i,i->', s*a, a)

print(result)


28


**5) Hadamard Product**

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,i->i', a, b)

print(result)


[ 4 10 18]


**6) Batch Matrix Multiplication**

In [19]:
import numpy as np

A = np.random.randn(3, 4, 5)  # 3 matrices of size 4x5
B = np.random.randn(3, 5, 6)  # 3 matrices of size 5x6

# Batch matrix multiplication
result = np.einsum('ijk,ikl->ijl', A, B)

print(result.shape)
# Output: (3, 4, 6)


(3, 4, 6)
