<a href="https://colab.research.google.com/github/pranukrish/CMPE258_DeepLearning/blob/main/Assignment2-b/EinSum_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This colab demonstrates the below operations using einsum in Pytorch



1.   Scalar Vector Multiplication
2.   Vector Vector Multiplications
3.   Outer Product
4.   Scalar Dot Product
5.   Hadamard Product
6.   Batch Matrix Multiplication
7.   Tensor Reduction
8.   Transpose
9.   Bilinear Transformation
10.   Attention
11.   Tree QN


**a) Scalar-Vector Multiplication**

In [3]:
import torch

a = torch.tensor([1, 2, 3])
s = torch.tensor([2])
result = torch.einsum('i,j->j', s, a)

print(result)



tensor([2, 4, 6])


**b) Vector-Vector multiplications**

In [4]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.einsum('i,i->', a, b)

print(result)


tensor(32)


**3) Outer Product**

In [5]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.einsum('i,j->ij', a, b)

print(result)


tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


**4) Scalar Dot Product**

In [6]:
import torch

a = torch.tensor([1, 2, 3])
s = 2
result = torch.einsum('i,i->', s*a, a)

print(result)


tensor(28)


**5) Hadamard Product**

In [7]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.einsum('i,i->i', a, b)

print(result)

tensor([ 4, 10, 18])


**6) Batch Matrix Multiplication**

In [8]:
import torch

A = torch.randn(3, 4, 5)  # 3 matrices of size 4x5
B = torch.randn(3, 5, 6)  # 3 matrices of size 5x6

# Batch matrix multiplication
result = torch.einsum('ijk,ikl->ijl', A, B)

print(result.shape)


torch.Size([3, 4, 6])


**7) Tensor Reduction**

In [9]:
import torch

# Define a tensor with shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# Reduce along the first dimension
y = torch.einsum('ijk->jk', x)

print(y.shape) 



torch.Size([4, 5])


**8) Transpose**

In [10]:
import torch

# Define a tensor with shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# Transpose the first and second dimensions
y = torch.einsum('ijk->jik', x)

print(y.shape) 


torch.Size([4, 3, 5])


**9) Bilinear Transformation**

In [11]:
import torch

# Define two tensors with shapes (3, 4) and (5, 4)
x = torch.randn(3, 4)
y = torch.randn(5, 4)

# Compute the bilinear transformation of the two tensors
z = torch.einsum('ij,kj->ik', x, y)

print(z.shape) 


torch.Size([3, 5])


**10) Attention**

In [12]:
import torch

# Define three tensors with shapes (batch_size, sequence_length, hidden_size)
queries = torch.randn(32, 10, 256)
keys = torch.randn(32, 20, 256)
values = torch.randn(32, 20, 256)

# Compute the dot product of queries and keys
scores = torch.einsum('bik,bjk->bij', queries, keys)

# Normalize the scores with a softmax function
scores_normalized = torch.softmax(scores, dim=-1)

# Compute the weighted sum of values
output = torch.einsum('bij,bjk->bik', scores_normalized, values)

print(output.shape) 


torch.Size([32, 10, 256])


**11) Tree-QN**

In [17]:
import torch

# Define the embeddings for the large corpus and the task-specific corpus
embeddings_large = torch.randn(10000, 300)
embeddings_small = torch.randn(100, 300)

# Compute the pairwise cosine similarities between the large corpus embeddings
sims_large = torch.einsum('ij,ij->i', embeddings_large, embeddings_large)

# Compute the pairwise cosine similarities between the task-specific corpus embeddings
sims_small = torch.einsum('ij,ij->i', embeddings_small, embeddings_small)

# Compute the cosine similarities between the large corpus embeddings and the task-specific corpus embeddings
sims = torch.einsum('ij,kj->ik', embeddings_small, embeddings_large)

# Compute the Tree QN matrix
tree_qn = torch.einsum('i,ik,l->il', sims_small, sims, sims_large)
#tree_qn = torch.einsum('i,ik,jk->ij', sims_small, sims, sims_large)

print(tree_qn.shape) 


torch.Size([100, 10000])
